# Generated by Django 2.1.10 on 2019-07-01 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('day', models.DateField(blank=True, default=datetime.datetime.now)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_diary.Food')),
            ],
        ),
    ]
