# Generated by Django 2.1.10 on 2019-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0003_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='meal',
            field=models.TextField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack')], default='snack'),
        ),
    ]
